stages:
- test
- pages

variables:
  YARN: yarn

promaster-react-test:
  image: node:8.1.3
  stage: test
  script:
    - echo $'@promaster:registry=https://npm.divid.se/\n//npm.divid.se/:always-auth=true\n//npm.divid.se/:_authToken="mB+l/jDgu/opzRXfn+VTVg3fT+CDHE5ZmVQCAEkSzfs=\"\n' > .npmrc
    - $YARN install --ignore-scripts
    - cd packages/promaster-react
    - $YARN run lint
    - $YARN run circular
    - $YARN run tsc
    - $YARN run tsc:test
    - $YARN run test

promaster-primitives-test:
  image: node:8.9.4
  stage: test
  script:
    - echo $'@promaster:registry=https://npm.divid.se/\n//npm.divid.se/:always-auth=true\n//npm.divid.se/:_authToken="mB+l/jDgu/opzRXfn+VTVg3fT+CDHE5ZmVQCAEkSzfs=\"\n' > .npmrc
    - $YARN install --ignore-scripts
    - cd packages/promaster-primitives
    - $YARN verify
  coverage: /^All files\s*\|\s*(\d+.\d+)/
  artifacts:
    paths:
      - coverage/

promaster-primitives-pages:
  stage: pages
  dependencies:
    - promaster-primitives-test
  script:
    - cd packages/promaster-primitives
    - mv coverage/lcov-report/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
