language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "12"
  - "10"
env:
  - TSVERSION=latest
  - TSVERSION=3.4.1 # Our minimum supported version
script:
  - yarn verify
after_success:
  - yarn report-coverage
