coverage:
  status:
    project:
      default:
        target: 10%
        threshold: null
      property:
        flags: property
        target: 10%
      property_filter_pretty:
        target: 10%
        flags: property_filter_pretty
      react_properties_selector:
        target: 10%
        flags: react_properties_selector
      react_property_selectors:
        flags: react_property_selectors
        target: 10%
      variant_listing:
        flags: variant_listing
        target: 10%
flags:
  property:
    paths:
      - packages/property/src
  property_filter_pretty:
    paths:
      - packages/property-filter-pretty/src
  react_properties_selector:
    paths:
      - packages/react-properties-selector/src
  react_property_selectors:
    paths:
      - packages/react-property-selectors/src
  variant_listing:
    paths:
      - packages/variant-listing/src
