stages:
- test

variables:
  YARN: node ./yarn.js

test:
  image: node:7.6.0
  stage: test
  script:
    - echo $'@promaster:registry=https://npm.divid.se/\n//npm.divid.se/:always-auth=true\n//npm.divid.se/:_authToken="mB+l/jDgu/opzRXfn+VTVg3fT+CDHE5ZmVQCAEkSzfs=\"\n' > .npmrc
    - $YARN install --ignore-scripts
    - $YARN run lint
    - $YARN run circular
    - $YARN run tsc
    - $YARN run tsc:test
    - $YARN run test
