stages:
- test
- pages

variables:
  YARN: node ./yarn.js

test:
  image: node:7.6.0
  stage: test
  script:
    - $YARN install --ignore-scripts
    - $YARN run lint
    - $YARN run circular
    - $YARN run tsc
    - $YARN run tsc:test
    - $YARN run test
  coverage: /^All files\s*\|\s*(\d+.\d+)/
  artifacts:
    paths:
      - coverage/
pages:
  stage: pages
  dependencies:
    - test
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
